.TH "crc32sum" "1" "11 April 2020" "crc32sum" "crc32sum"

.SH NAME
.B crc32sum
- compute and check CRC32 message checksums


.SH SYNOPSIS
.SY crc32sum
.OP -r
.OP -p
.IR FILE ...
.br
.SY crc32sum
.B -c
.RB [ -q
|
.BR -s ]
.OP -p
.IR FILE ...
.YS


.SH DESCRIPTION
.B crc32sum
is a simple utility that calculates the
.I CRC-32
checksum (using the
.I 0xedb88320
polynomial) for each of the given files or for the data read from the
standard input. It aims to work more or less in the same way as the
.B md5sum
or
.B sha1sum
utilities do.


.SH OPTIONS
.B \-c
.IR FILE ,
.B \--check
.I FILE
.RS 4
Read the
.I CRC-32
sums from the
.I FILE
and check them.
.RE

.BR \-r ,
.B \--recursive
.RS 4
Treat the
.I FILE
as a directory and generate the
.I CRC-32
sums for all files in it.
.RE

.BR \-p ,
.B \--progress
.RS 4
Show a progressbar similar to the one shown by
.BR apt (1).
.RE

.BR \-h ,
.B \--help
.RS 4
Show usage information and exit.
.RE

.BR \-v ,
.B \--version
.RS 4
Show version number and exit.
.RE

The following options are useful only when verifying checksums:

.BR \-q ,
.B \--quiet
.RS 4
Do not print OK for each successfully verified file.
.RE

.BR \-s ,
.B \--status
.RS 4
Do not output anything, the status code shows success.
.RE


.SH SECURITY WARNING
Though the utility does use a similar interface to many hash-calculation
utilities (e.g.,
.B md5sum
or
.BR sha1sum ),
it should be kept in mind that
.I CRC-32
is not a cryptographic hash. The program is not intended to protect against
the malicious modification of files but to provide a fast error detection in
data transmission or storage.


.SH REPORTING BUGS
If you encounter a bug, you should make sure that you are using the latest
version of the software. If you are and the bug is still present, you can
report it on the GitLab issues tracker:
.IR https://gitlab.com/vlastavesely/crc32sum/issues .


.SH LICENSE AND WARRANTY
Copyright © 2018-2021  Vlasta Vesely
.RI < vlastavesely@protonmail.ch >

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License version 2 as published by the
Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
