crc32sum(1)
===========
:manmanual: crc32sum

NAME
----
crc32sum - compute and check CRC32 message checksums


SYNOPSIS
--------
*crc32sum* [*-r*] [*-p*] [*-c* 'FILE'] [*-q*] [*-s*] ['FILE']...


DESCRIPTION
-----------
*crc32sum* is a simple utility that calculates the CRC-32 checksum (using the
'0xedb88320' polynomial) for each of the given files or for read data from the
standard input. It aims to work more or less in the same way as the *md5sum*
or *sha1sum* utilities do.


OPTIONS
-------
*-c* 'FILE', *--check* 'FILE'::
Read CRC32 sums from the FILE and check them.

*-r*, *--recursive*::
Generate CRC32 sums for all files in given directories.

*-p*, *--progress*::
Show a progressbar.

*-h*, *--help*::
Show usage information and exit.

*-v*, *--version*::
Show version number and exit.

The following options are useful only when verifying checksums:

*-q*, *--quiet*::
Don't print OK for each successfully verified file.

*-s*, *--status*::
Don't output anything, status code shows success.


WARNING
-------
Note that the CRC32 checksum is merely used for error detection in
transmission and storage. It is not intended to guard against the malicious
modification of files (i.e., it is not a cryptographic hash).


AUTHOR
------
Copyright (c) 2018  Vlasta Vesely <vlastavesely@protonmail.ch>


REPORTING BUGS
--------------
If you encounter a bug, you should make sure that you are using the latest
version of the software. If you do and the bug is still present, you can
report it using either the issues tracker on GitLab or GitHub.

GitLab: <https://gitlab.com/vlastavesely/crc32sum/issues> +
GitHub: <https://github.com/vlastavesely/crc32sum/issues>


LICENSE AND WARRANTY
--------------------
This software is released under the terms of the GPL license version 2 as
published by the Free Software Foundation.
See <https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt> for more details.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
